import Jasmine from 'jasmine';
import * as url from 'url';
import { ConnectionOptions } from '../lib/registry.mjs';
process.specs = new WeakMap();
const __dirname = url.fileURLToPath(new URL('./', import.meta.url));
const jasmine = new Jasmine({ projectBaseDir: __dirname });
jasmine.jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;
jasmine.addMatchingSpecFiles(['**/*.spec.mjs']);
process.connectionOptions = new ConnectionOptions(3, 10000, 'localhost', 8080, 'localhost', 8080);
jasmine.execute();
